version: '3.7'

services:
  medic-os:
    container_name: medic-os
    image: medicmobile/medic-os:cht-3.9.0-rc.2
    working_dir: /srv
    restart: unless-stopped
    network_mode: host
    volumes:
      - medic-data:/srv
      - './tls-certs/:/etc/tls-certs/'    
    depends_on:
      - haproxy
    environment:
      - DOCKER_NETWORK_NAME=localhost
      - DOCKER_COUCHDB_ADMIN_PASSWORD=$DOCKER_COUCHDB_ADMIN_PASSWORD

  haproxy:
    container_name: haproxy
    image: medicmobile/haproxy:rc-1.17
    restart: unless-stopped
    network_mode: host
    volumes:
      - medic-data:/srv    
      - './tls-certs/:/etc/tls-certs/'    
    environment:
      - COUCHDB_HOST=localhost
      - HA_PASSWORD=$DOCKER_COUCHDB_ADMIN_PASSWORD

volumes:
  medic-data:
    name: medic-data
