version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: "host"
    restart: unless-stopped
    environment:
      TZ: 'Africa/Nairobi'
      WEBPASSWORD: 'test123'
      WEB_PORT: 8081
      DNSMASQ_USER: root 
      PIHOLE_UID: 0 
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      - './tls-certs/:/etc/tls-certs/'
      - './etc-lighttpd/external.conf:/etc/lighttpd/external.conf'
    cap_add:
      - NET_ADMIN
